In [4]:
%reset

Once deleted, variables cannot be recovered. Proceed (y/[n])? y


In [6]:
import numpy as np
from random import random
#CPU version
import tensorflow as tf 
from sklearn.model_selection import train_test_split



def generate_dataset(num_samples, test_size):
    #create a dataset to train a network for the sum operation
    #list comprehension
    #array([[0.1, 0.2], [0.3,0.4]])
    x = np.array([[random() / 2 for _ in range(2)] for _ in range(num_samples)])
    #array([[0.3],[0.7])
    y = np.array([[i[0] + i[1]] for i in x])
    x_train, x_test, y_train, y_test = train_test_split(x ,y, test_size = test_size)
    return x_train, x_test, y_train, y_test

if __name__ == "__main__":
    x_train, x_test, y_train, y_test = generate_dataset(5000,0.3)
    print("x_test: \n {}".format(x_test))
    print("y_test: \n {}".format(y_test))
    
    #build model: 2 -> 5 -> 1
    #keras is a high level library that sits on top of tensorflow
    model = tf.keras.Sequential([
        tf.keras.layers.Dense(5, input_dim = 2, activation = "sigmoid"),
        tf.keras.layers.Dense(1, activation = "sigmoid")
    ])
    
    #compile the model
    optimizer = tf.keras.optimizers.SGD(learning_rate = 0.1)
    model.compile(optimizer = optimizer, loss = "MSE")
    
    #train model
    model.fit(x_train, y_train, epochs = 100)

    #evaluate model
    print("\nModel evaluation")
    model.evaluate(x_test, y_test, verbose=True)
    
    #make predictions
    data = np.array([[0.112, 0.245], [0.22,0.34]])
    predictions = model.predict(data)
    
    
    print("\nSome predictions: ")
    for d, p in zip(data,predictions):
        print("{} + {} = {}".format(d[0], d[1], p[0]))
    

x_test: 
 [[0.25191012 0.10448258]
 [0.13924263 0.48099688]
 [0.38310336 0.45342404]
 ...
 [0.02911909 0.03387246]
 [0.1435098  0.49156796]
 [0.36140214 0.15845179]]
y_test: 
 [[0.3563927 ]
 [0.62023952]
 [0.8365274 ]
 ...
 [0.06299154]
 [0.63507775]
 [0.51985394]]
Epoch 1/100
110/110 [==============================] - 0s 1ms/step - loss: 0.0402
Epoch 2/100
110/110 [==============================] - 0s 1ms/step - loss: 0.0396
Epoch 3/100
110/110 [==============================] - 0s 1ms/step - loss: 0.0392
Epoch 4/100
110/110 [==============================] - 0s 1ms/step - loss: 0.0388
Epoch 5/100
110/110 [==============================] - 0s 1ms/step - loss: 0.0384
Epoch 6/100
110/110 [==============================] - 0s 2ms/step - loss: 0.0379
Epoch 7/100
110/110 [==============================] - 0s 2ms/step - loss: 0.0375
Epoch 8/100
110/110 [==============================] - 0s 1ms/step - loss: 0.0370
Epoch 9/100
110/110 [==============================] - 0s 1ms/step - loss: 0.0

Epoch 96/100
110/110 [==============================] - 0s 815us/step - loss: 6.9127e-04
Epoch 97/100
110/110 [==============================] - 0s 874us/step - loss: 6.7104e-04
Epoch 98/100
110/110 [==============================] - 0s 1ms/step - loss: 6.5198e-04
Epoch 99/100
110/110 [==============================] - 0s 2ms/step - loss: 6.3488e-04
Epoch 100/100
110/110 [==============================] - 0s 3ms/step - loss: 6.1855e-04

Model evaluation
47/47 [==============================] - 0s 1ms/step - loss: 5.9622e-04

Some predictions: 
0.112 + 0.245 = 0.35660475492477417
0.22 + 0.34 = 0.5696184039115906
